# Generated by Django 3.1.2 on 2020-11-21 09:22

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlatImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bedroom_img', models.ImageField(max_length=255, upload_to='')),
                ('kitchen_img', models.ImageField(max_length=255, upload_to='')),
                ('bathroom_img', models.ImageField(max_length=255, upload_to='')),
                ('livingroom_img', models.ImageField(max_length=255, upload_to='')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('municipality', models.CharField(max_length=100)),
                ('ward_no', models.IntegerField()),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_img', models.ImageField(max_length=255, upload_to='')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=10)),
                ('price', models.IntegerField()),
                ('size', models.DecimalField(decimal_places=2, max_digits=5)),
                ('water_facility', models.BooleanField(default=False)),
                ('electricity', models.BooleanField(default=False)),
                ('Parking_facility', models.BooleanField(default=False)),
                ('short_description', models.TextField(max_length=190)),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='add_property.location')),
                ('room_images', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='add_property.roomimage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyFlat',
            fields=[
                ('flat_id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=10)),
                ('price', models.IntegerField()),
                ('bedroom_no', models.IntegerField()),
                ('kitchen_no', models.IntegerField()),
                ('bathroom_no', models.IntegerField()),
                ('livingroom_no', models.IntegerField()),
                ('water_facility', models.BooleanField(default=False)),
                ('electricity', models.BooleanField(default=False)),
                ('Parking_facility', models.BooleanField(default=False)),
                ('short_description', models.TextField(max_length=190)),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('flat_images', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='add_property.flatimage')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='add_property.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommentsRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='add_property.propertyroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommentsFlat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='add_property.propertyflat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
